"""events log

Revision ID: d64edacfd00a
Revises: 
Create Date: 2026-06-09 18:19:06.988644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64edacfd00a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('actor', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.create_index(op.f('ix_events_project'), 'events', ['project'], unique=False)
    op.create_index(op.f('ix_events_spec'), 'events', ['spec'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_spec'), table_name='events')
    op.drop_index(op.f('ix_events_project'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
